### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by Jetradj** [JannesBonk/Medusa.uno#8]
Can the source be downloaded from somewhere? Medusa.uno has worked in csgo for a long time after cs2 release, but recently broke with pattern errors.

**Comment by JannesBonk** [comment]
> Can the source be downloaded from somewhere? Medusa.uno has worked in csgo for a long time after cs2 release, but recently broke with pattern errors.

ill fix it when i have time

**Comment by Jetradj** [comment]
Alright, just out of curiosity it a short fix and what do "failed to find pattern #1!" and "failed to find pattern #2!" even mean?

**Comment by JannesBonk** [comment]
> Alright, just out of curiosity it a short fix and what do "failed to find pattern #1!" and "failed to find pattern #2!" even mean?

those errors basically mean that the cheat is outdated and needs patching. I recommend checking out the new Medusa.uno variant, made by other devs, similar to this version, but with alot of improvements.
Here is a discord link: https://discord.com/invite/yzVSsvrJ

**Comment by Jetradj** [comment]
Do old cfgs work on the newer versions?

**Comment by Jetradj** [comment]
and is there a download for a working medusa.uno available on the discord?

**Comment by tizzyxyz** [comment]
whats the new discord link?
